from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 650))
        MainWindow.setMaximumSize(QtCore.QSize(800, 650))
        font = QtGui.QFont()
        font.setFamily("Pricedown Rus")
        font.setPointSize(36)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 650))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 650))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 810, 660))
        self.stackedWidget.setMinimumSize(QtCore.QSize(810, 660))
        self.stackedWidget.setMaximumSize(QtCore.QSize(800, 650))
        self.stackedWidget.setStyleSheet("background-color: wheat;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.FINAL_PAGE = QtWidgets.QWidget()
        self.FINAL_PAGE.setObjectName("FINAL_PAGE")
        self.MP3_LOGO = QtWidgets.QLabel(self.FINAL_PAGE)
        self.MP3_LOGO.setGeometry(QtCore.QRect(10, 10, 201, 191))
        self.MP3_LOGO.setText("")
        self.MP3_LOGO.setPixmap(QtGui.QPixmap(":/MP3_FINAL_PAGE/png_files/mp3_final_oage.png"))
        self.MP3_LOGO.setObjectName("MP3_LOGO")
        self.FINAL_PAGE_LABEL = QtWidgets.QLabel(self.FINAL_PAGE)
        self.FINAL_PAGE_LABEL.setGeometry(QtCore.QRect(250, 30, 531, 141))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.FINAL_PAGE_LABEL.setFont(font)
        self.FINAL_PAGE_LABEL.setObjectName("FINAL_PAGE_LABEL")
        self.BTN_USE_AGAIN = QtWidgets.QPushButton(self.FINAL_PAGE)
        self.BTN_USE_AGAIN.setGeometry(QtCore.QRect(90, 470, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.BTN_USE_AGAIN.setFont(font)
        self.BTN_USE_AGAIN.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 40%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #069323;\n"
"}")
        self.BTN_USE_AGAIN.setObjectName("BTN_USE_AGAIN")
        self.BTN_EXIT = QtWidgets.QPushButton(self.FINAL_PAGE)
        self.BTN_EXIT.setGeometry(QtCore.QRect(500, 470, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.BTN_EXIT.setFont(font)
        self.BTN_EXIT.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 40%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ff3131;\n"
"}")
        self.BTN_EXIT.setObjectName("BTN_EXIT")
        self.stackedWidget.addWidget(self.FINAL_PAGE)
        self.FIRST_PAGE = QtWidgets.QWidget()
        self.FIRST_PAGE.setObjectName("FIRST_PAGE")
        self.docx_to_mp3_btn = QtWidgets.QPushButton(self.FIRST_PAGE)
        self.docx_to_mp3_btn.setGeometry(QtCore.QRect(270, 350, 270, 80))
        self.docx_to_mp3_btn.setMinimumSize(QtCore.QSize(250, 80))
        self.docx_to_mp3_btn.setMaximumSize(QtCore.QSize(300, 80))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.docx_to_mp3_btn.setFont(font)
        self.docx_to_mp3_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.docx_to_mp3_btn.setMouseTracking(False)
        self.docx_to_mp3_btn.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 30%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b38566;\n"
"}")
        self.docx_to_mp3_btn.setIconSize(QtCore.QSize(16, 16))
        self.docx_to_mp3_btn.setObjectName("docx_to_mp3_btn")
        self.label_voicer = QtWidgets.QLabel(self.FIRST_PAGE)
        self.label_voicer.setGeometry(QtCore.QRect(50, 10, 731, 71))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_voicer.setFont(font)
        self.label_voicer.setObjectName("label_voicer")
        self.mp3_logo_2 = QtWidgets.QLabel(self.FIRST_PAGE)
        self.mp3_logo_2.setGeometry(QtCore.QRect(240, 140, 311, 171))
        self.mp3_logo_2.setText("")
        self.mp3_logo_2.setPixmap(QtGui.QPixmap(":/MP3_FIRST_PAGE/png_files/mp3_first_page.png"))
        self.mp3_logo_2.setObjectName("mp3_logo_2")
        self.pdf_to_mp3_btn = QtWidgets.QPushButton(self.FIRST_PAGE)
        self.pdf_to_mp3_btn.setGeometry(QtCore.QRect(270, 550, 270, 80))
        self.pdf_to_mp3_btn.setMinimumSize(QtCore.QSize(270, 80))
        self.pdf_to_mp3_btn.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pdf_to_mp3_btn.setFont(font)
        self.pdf_to_mp3_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pdf_to_mp3_btn.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 30%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b38566;\n"
"}")
        self.pdf_to_mp3_btn.setIconSize(QtCore.QSize(16, 16))
        self.pdf_to_mp3_btn.setObjectName("pdf_to_mp3_btn")
        self.txt_to_mp3_btn = QtWidgets.QPushButton(self.FIRST_PAGE)
        self.txt_to_mp3_btn.setGeometry(QtCore.QRect(270, 450, 270, 80))
        self.txt_to_mp3_btn.setMinimumSize(QtCore.QSize(270, 80))
        self.txt_to_mp3_btn.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.txt_to_mp3_btn.setFont(font)
        self.txt_to_mp3_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.txt_to_mp3_btn.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 30%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b38566;\n"
"}")
        self.txt_to_mp3_btn.setIconSize(QtCore.QSize(16, 16))
        self.txt_to_mp3_btn.setObjectName("txt_to_mp3_btn")
        self.stackedWidget.addWidget(self.FIRST_PAGE)
        self.DOCX_TO_MP3 = QtWidgets.QWidget()
        self.DOCX_TO_MP3.setObjectName("DOCX_TO_MP3")
        self.OUTPUT_PATH_LABEL_DOCX = QtWidgets.QLabel(self.DOCX_TO_MP3)
        self.OUTPUT_PATH_LABEL_DOCX.setGeometry(QtCore.QRect(50, 260, 551, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OUTPUT_PATH_LABEL_DOCX.setFont(font)
        self.OUTPUT_PATH_LABEL_DOCX.setObjectName("OUTPUT_PATH_LABEL_DOCX")
        self.BTN_SELECT_OUTPUT_PATH_DOCX = QtWidgets.QPushButton(self.DOCX_TO_MP3)
        self.BTN_SELECT_OUTPUT_PATH_DOCX.setGeometry(QtCore.QRect(680, 290, 21, 21))
        self.BTN_SELECT_OUTPUT_PATH_DOCX.setStyleSheet("background-color: white")
        self.BTN_SELECT_OUTPUT_PATH_DOCX.setObjectName("BTN_SELECT_OUTPUT_PATH_DOCX")
        self.DOCX_FILE_DUBBING = QtWidgets.QPushButton(self.DOCX_TO_MP3)
        self.DOCX_FILE_DUBBING.setGeometry(QtCore.QRect(490, 500, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.DOCX_FILE_DUBBING.setFont(font)
        self.DOCX_FILE_DUBBING.setStyleSheet("QPushButton {\n"
                                             
"    background-color: #a97653;\n"
"    border-radius: 40%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #069323;\n"
"}")
        self.DOCX_FILE_DUBBING.setObjectName("DOCX_FILE_DUBBING")
        self.INPUT_PATH_LABEL_DOCX = QtWidgets.QLabel(self.DOCX_TO_MP3)
        self.INPUT_PATH_LABEL_DOCX.setGeometry(QtCore.QRect(50, 110, 541, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.INPUT_PATH_LABEL_DOCX.setFont(font)
        self.INPUT_PATH_LABEL_DOCX.setObjectName("INPUT_PATH_LABEL_DOCX")
        self.BTN_SELECT_INPUT_PATH_DOCX = QtWidgets.QPushButton(self.DOCX_TO_MP3)
        self.BTN_SELECT_INPUT_PATH_DOCX.setGeometry(QtCore.QRect(680, 140, 21, 21))
        self.BTN_SELECT_INPUT_PATH_DOCX.setStyleSheet("background-color: white")
        self.BTN_SELECT_INPUT_PATH_DOCX.setObjectName("BTN_SELECT_INPUT_PATH_DOCX")
        self.DOCX_BACK = QtWidgets.QPushButton(self.DOCX_TO_MP3)
        self.DOCX_BACK.setGeometry(QtCore.QRect(50, 500, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.DOCX_BACK.setFont(font)
        self.DOCX_BACK.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 40%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"}")
        self.DOCX_BACK.setObjectName("DOCX_BACK")
        self.INPUT_PATH_INPUT_DOCX_ = QtWidgets.QLineEdit(self.DOCX_TO_MP3)
        self.INPUT_PATH_INPUT_DOCX_.setGeometry(QtCore.QRect(50, 140, 621, 22))
        self.INPUT_PATH_INPUT_DOCX_.setText("")
        self.INPUT_PATH_INPUT_DOCX_.setObjectName("INPUT_PATH_INPUT_DOCX_")
        self.INPUT_PATH_OUTPUT_DOCX = QtWidgets.QLineEdit(self.DOCX_TO_MP3)
        self.INPUT_PATH_OUTPUT_DOCX.setGeometry(QtCore.QRect(50, 290, 621, 22))
        self.INPUT_PATH_OUTPUT_DOCX.setText("")
        self.INPUT_PATH_OUTPUT_DOCX.setObjectName("INPUT_PATH_OUTPUT_DOCX")
        self.RADIO_RU_LANG_DOCX = QtWidgets.QRadioButton(self.DOCX_TO_MP3)
        self.RADIO_RU_LANG_DOCX.setGeometry(QtCore.QRect(50, 410, 80, 21))
        self.RADIO_RU_LANG_DOCX.setMinimumSize(QtCore.QSize(80, 0))
        self.RADIO_RU_LANG_DOCX.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RADIO_RU_LANG_DOCX.setFont(font)
        self.RADIO_RU_LANG_DOCX.setStyleSheet("width: 20px;\n"
"height: 20px;\n"
" border: 0.1mm solid black;")
        self.RADIO_RU_LANG_DOCX.setObjectName("RADIO_RU_LANG_DOCX")
        self.RADIO_EN_LANG_DOCX = QtWidgets.QRadioButton(self.DOCX_TO_MP3)
        self.RADIO_EN_LANG_DOCX.setGeometry(QtCore.QRect(50, 440, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RADIO_EN_LANG_DOCX.setFont(font)
        self.RADIO_EN_LANG_DOCX.setObjectName("RADIO_EN_LANG_DOCX")
        self.CHOOSE_LANG_DOCX = QtWidgets.QLabel(self.DOCX_TO_MP3)
        self.CHOOSE_LANG_DOCX.setGeometry(QtCore.QRect(50, 370, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CHOOSE_LANG_DOCX.setFont(font)
        self.CHOOSE_LANG_DOCX.setObjectName("CHOOSE_LANG_DOCX")
        self.BTN_SELECT_OUTPUT_PATH_DOCX.raise_()
        self.DOCX_FILE_DUBBING.raise_()
        self.INPUT_PATH_LABEL_DOCX.raise_()
        self.BTN_SELECT_INPUT_PATH_DOCX.raise_()
        self.DOCX_BACK.raise_()
        self.OUTPUT_PATH_LABEL_DOCX.raise_()
        self.INPUT_PATH_INPUT_DOCX_.raise_()
        self.INPUT_PATH_OUTPUT_DOCX.raise_()
        self.RADIO_RU_LANG_DOCX.raise_()
        self.RADIO_EN_LANG_DOCX.raise_()
        self.CHOOSE_LANG_DOCX.raise_()
        self.stackedWidget.addWidget(self.DOCX_TO_MP3)
        self.TXT_TO_MP3 = QtWidgets.QWidget()
        self.TXT_TO_MP3.setObjectName("TXT_TO_MP3")
        self.BTN_SELECT_OUTPUT_PATH_TXT = QtWidgets.QPushButton(self.TXT_TO_MP3)
        self.BTN_SELECT_OUTPUT_PATH_TXT.setGeometry(QtCore.QRect(680, 290, 21, 21))
        self.BTN_SELECT_OUTPUT_PATH_TXT.setStyleSheet("background-color: white")
        self.BTN_SELECT_OUTPUT_PATH_TXT.setObjectName("BTN_SELECT_OUTPUT_PATH_TXT")
        self.BTN_SELECT_INPUT_PATH_TXT = QtWidgets.QPushButton(self.TXT_TO_MP3)
        self.BTN_SELECT_INPUT_PATH_TXT.setGeometry(QtCore.QRect(680, 140, 21, 21))
        self.BTN_SELECT_INPUT_PATH_TXT.setStyleSheet("background-color: white")
        self.BTN_SELECT_INPUT_PATH_TXT.setObjectName("BTN_SELECT_INPUT_PATH_TXT")
        self.TXT_FILE_DUBBING = QtWidgets.QPushButton(self.TXT_TO_MP3)
        self.TXT_FILE_DUBBING.setGeometry(QtCore.QRect(490, 500, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.TXT_FILE_DUBBING.setFont(font)
        self.TXT_FILE_DUBBING.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 40%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #069323;\n"
"}")
        self.TXT_FILE_DUBBING.setObjectName("TXT_FILE_DUBBING")
        self.INPUT_PATH_LABEL_TXT = QtWidgets.QLabel(self.TXT_TO_MP3)
        self.INPUT_PATH_LABEL_TXT.setGeometry(QtCore.QRect(50, 110, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.INPUT_PATH_LABEL_TXT.setFont(font)
        self.INPUT_PATH_LABEL_TXT.setObjectName("INPUT_PATH_LABEL_TXT")
        self.OUTPUT_PATH_LABEL_TXT = QtWidgets.QLabel(self.TXT_TO_MP3)
        self.OUTPUT_PATH_LABEL_TXT.setGeometry(QtCore.QRect(50, 260, 551, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OUTPUT_PATH_LABEL_TXT.setFont(font)
        self.OUTPUT_PATH_LABEL_TXT.setObjectName("OUTPUT_PATH_LABEL_TXT")
        self.TXT_BACK = QtWidgets.QPushButton(self.TXT_TO_MP3)
        self.TXT_BACK.setGeometry(QtCore.QRect(50, 500, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.TXT_BACK.setFont(font)
        self.TXT_BACK.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 40%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"}")
        self.TXT_BACK.setObjectName("TXT_BACK")
        self.INPUT_PATH_INPUT_TXT_ = QtWidgets.QLineEdit(self.TXT_TO_MP3)
        self.INPUT_PATH_INPUT_TXT_.setGeometry(QtCore.QRect(50, 140, 621, 22))
        self.INPUT_PATH_INPUT_TXT_.setText("")
        self.INPUT_PATH_INPUT_TXT_.setObjectName("INPUT_PATH_INPUT_TXT_")
        self.INPUT_PATH_OUTPUT_TXT = QtWidgets.QLineEdit(self.TXT_TO_MP3)
        self.INPUT_PATH_OUTPUT_TXT.setGeometry(QtCore.QRect(50, 290, 621, 22))
        self.INPUT_PATH_OUTPUT_TXT.setText("")
        self.INPUT_PATH_OUTPUT_TXT.setObjectName("INPUT_PATH_OUTPUT_TXT")
        self.RADIO_EN_LANG_TXT = QtWidgets.QRadioButton(self.TXT_TO_MP3)
        self.RADIO_EN_LANG_TXT.setGeometry(QtCore.QRect(50, 440, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RADIO_EN_LANG_TXT.setFont(font)
        self.RADIO_EN_LANG_TXT.setObjectName("RADIO_EN_LANG_TXT")
        self.RADIO_RU_LANG_TXT = QtWidgets.QRadioButton(self.TXT_TO_MP3)
        self.RADIO_RU_LANG_TXT.setGeometry(QtCore.QRect(50, 410, 80, 21))
        self.RADIO_RU_LANG_TXT.setMinimumSize(QtCore.QSize(80, 0))
        self.RADIO_RU_LANG_TXT.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RADIO_RU_LANG_TXT.setFont(font)
        self.RADIO_RU_LANG_TXT.setStyleSheet("width: 20px;\n"
"height: 20px;\n"
" border: 0.1mm solid black;")
        self.RADIO_RU_LANG_TXT.setObjectName("RADIO_RU_LANG_TXT")
        self.CHOOSE_LANG_LABEL_TXT = QtWidgets.QLabel(self.TXT_TO_MP3)
        self.CHOOSE_LANG_LABEL_TXT.setGeometry(QtCore.QRect(50, 370, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CHOOSE_LANG_LABEL_TXT.setFont(font)
        self.CHOOSE_LANG_LABEL_TXT.setObjectName("CHOOSE_LANG_LABEL_TXT")
        self.stackedWidget.addWidget(self.TXT_TO_MP3)
        self.PDF_TO_MP3 = QtWidgets.QWidget()
        self.PDF_TO_MP3.setObjectName("PDF_TO_MP3")
        self.OUTPUT_PATH_LABEL_PDF = QtWidgets.QLabel(self.PDF_TO_MP3)
        self.OUTPUT_PATH_LABEL_PDF.setGeometry(QtCore.QRect(50, 260, 551, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OUTPUT_PATH_LABEL_PDF.setFont(font)
        self.OUTPUT_PATH_LABEL_PDF.setObjectName("OUTPUT_PATH_LABEL_PDF")
        self.BTN_SELECT_INPUT_PATH_PDF = QtWidgets.QPushButton(self.PDF_TO_MP3)
        self.BTN_SELECT_INPUT_PATH_PDF.setGeometry(QtCore.QRect(680, 140, 21, 21))
        self.BTN_SELECT_INPUT_PATH_PDF.setStyleSheet("background-color: white")
        self.BTN_SELECT_INPUT_PATH_PDF.setObjectName("BTN_SELECT_INPUT_PATH_PDF")
        self.BTN_SELECT_OUTPUT_PATH_PDF = QtWidgets.QPushButton(self.PDF_TO_MP3)
        self.BTN_SELECT_OUTPUT_PATH_PDF.setGeometry(QtCore.QRect(680, 290, 21, 21))
        self.BTN_SELECT_OUTPUT_PATH_PDF.setStyleSheet("background-color: white")
        self.BTN_SELECT_OUTPUT_PATH_PDF.setObjectName("BTN_SELECT_OUTPUT_PATH_PDF")
        self.INPUT_PATH_LABEL_PDF = QtWidgets.QLabel(self.PDF_TO_MP3)
        self.INPUT_PATH_LABEL_PDF.setGeometry(QtCore.QRect(50, 110, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.INPUT_PATH_LABEL_PDF.setFont(font)
        self.INPUT_PATH_LABEL_PDF.setObjectName("INPUT_PATH_LABEL_PDF")
        self.PDF_FILE_DUBBING = QtWidgets.QPushButton(self.PDF_TO_MP3)
        self.PDF_FILE_DUBBING.setGeometry(QtCore.QRect(490, 500, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.PDF_FILE_DUBBING.setFont(font)
        self.PDF_FILE_DUBBING.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 40%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #069323;\n"
"}")
        self.PDF_FILE_DUBBING.setObjectName("PDF_FILE_DUBBING")
        self.PDF_BACK = QtWidgets.QPushButton(self.PDF_TO_MP3)
        self.PDF_BACK.setGeometry(QtCore.QRect(50, 500, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.PDF_BACK.setFont(font)
        self.PDF_BACK.setStyleSheet("QPushButton {\n"
"    background-color: #a97653;\n"
"    border-radius: 40%;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"}")
        self.PDF_BACK.setObjectName("PDF_BACK")
        self.INPUT_PATH_INPUT_PDF_ = QtWidgets.QLineEdit(self.PDF_TO_MP3)
        self.INPUT_PATH_INPUT_PDF_.setGeometry(QtCore.QRect(50, 140, 621, 22))
        self.INPUT_PATH_INPUT_PDF_.setText("")
        self.INPUT_PATH_INPUT_PDF_.setObjectName("INPUT_PATH_INPUT_PDF_")
        self.INPUT_PATH_OUTPUT_PDF = QtWidgets.QLineEdit(self.PDF_TO_MP3)
        self.INPUT_PATH_OUTPUT_PDF.setGeometry(QtCore.QRect(50, 290, 621, 22))
        self.INPUT_PATH_OUTPUT_PDF.setText("")
        self.INPUT_PATH_OUTPUT_PDF.setObjectName("INPUT_PATH_OUTPUT_PDF")
        self.RADIO_EN_LANG_PDF = QtWidgets.QRadioButton(self.PDF_TO_MP3)
        self.RADIO_EN_LANG_PDF.setGeometry(QtCore.QRect(50, 440, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RADIO_EN_LANG_PDF.setFont(font)
        self.RADIO_EN_LANG_PDF.setObjectName("RADIO_EN_LANG_PDF")
        self.CHECKBOX_RU_LANG_PDF = QtWidgets.QRadioButton(self.PDF_TO_MP3)
        self.CHECKBOX_RU_LANG_PDF.setGeometry(QtCore.QRect(50, 410, 80, 21))
        self.CHECKBOX_RU_LANG_PDF.setMinimumSize(QtCore.QSize(80, 0))
        self.CHECKBOX_RU_LANG_PDF.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CHECKBOX_RU_LANG_PDF.setFont(font)
        self.CHECKBOX_RU_LANG_PDF.setStyleSheet("width: 20px;\n"
"height: 20px;\n"
" border: 0.1mm solid black;")
        self.CHECKBOX_RU_LANG_PDF.setObjectName("CHECKBOX_RU_LANG_PDF")
        self.RADIO_LANG_LABEL_PDF = QtWidgets.QLabel(self.PDF_TO_MP3)
        self.RADIO_LANG_LABEL_PDF.setGeometry(QtCore.QRect(50, 370, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RADIO_LANG_LABEL_PDF.setFont(font)
        self.RADIO_LANG_LABEL_PDF.setObjectName("RADIO_LANG_LABEL_PDF")
        self.BTN_SELECT_INPUT_PATH_PDF.raise_()
        self.BTN_SELECT_OUTPUT_PATH_PDF.raise_()
        self.INPUT_PATH_LABEL_PDF.raise_()
        self.PDF_FILE_DUBBING.raise_()
        self.OUTPUT_PATH_LABEL_PDF.raise_()
        self.PDF_BACK.raise_()
        self.INPUT_PATH_INPUT_PDF_.raise_()
        self.INPUT_PATH_OUTPUT_PDF.raise_()
        self.RADIO_EN_LANG_PDF.raise_()
        self.CHECKBOX_RU_LANG_PDF.raise_()
        self.RADIO_LANG_LABEL_PDF.raise_()
        self.stackedWidget.addWidget(self.PDF_TO_MP3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FINAL_PAGE_LABEL.setText(_translate("MainWindow", "File mp3 was successfully saved"))
        self.BTN_USE_AGAIN.setText(_translate("MainWindow", "Use again"))
        self.BTN_EXIT.setText(_translate("MainWindow", "Exit"))
        self.docx_to_mp3_btn.setText(_translate("MainWindow", ".DOCX TO .MP3"))
        self.label_voicer.setText(_translate("MainWindow", "Voicer from .docx, .txt, .pdf to .mp3"))
        self.pdf_to_mp3_btn.setText(_translate("MainWindow", ".PDF TO .MP3"))
        self.txt_to_mp3_btn.setText(_translate("MainWindow", ".TXT TO .MP3"))
        self.OUTPUT_PATH_LABEL_DOCX.setText(_translate("MainWindow", "Select folder path, where you want to safe a .mp3 file:"))
        self.BTN_SELECT_OUTPUT_PATH_DOCX.setText(_translate("MainWindow", "..."))
        self.DOCX_FILE_DUBBING.setText(_translate("MainWindow", "Voice out file"))
        self.INPUT_PATH_LABEL_DOCX.setText(_translate("MainWindow", "Select docx file path, which one you want to voice out:"))
        self.BTN_SELECT_INPUT_PATH_DOCX.setText(_translate("MainWindow", "..."))
        self.DOCX_BACK.setText(_translate("MainWindow", "Back"))
        self.RADIO_RU_LANG_DOCX.setText(_translate("MainWindow", "Russian"))
        self.RADIO_EN_LANG_DOCX.setText(_translate("MainWindow", "Engilsh"))
        self.CHOOSE_LANG_DOCX.setText(_translate("MainWindow", "Choose a language"))
        self.BTN_SELECT_OUTPUT_PATH_TXT.setText(_translate("MainWindow", "..."))
        self.BTN_SELECT_INPUT_PATH_TXT.setText(_translate("MainWindow", "..."))
        self.TXT_FILE_DUBBING.setText(_translate("MainWindow", "Voice out file"))
        self.INPUT_PATH_LABEL_TXT.setText(_translate("MainWindow", "Select txt file path, which one you want to voice out:"))
        self.OUTPUT_PATH_LABEL_TXT.setText(_translate("MainWindow", "Select folder path, where you want to safe a .mp3 file:"))
        self.TXT_BACK.setText(_translate("MainWindow", "Back"))
        self.RADIO_EN_LANG_TXT.setText(_translate("MainWindow", "Engilsh"))
        self.RADIO_RU_LANG_TXT.setText(_translate("MainWindow", "Russian"))
        self.CHOOSE_LANG_LABEL_TXT.setText(_translate("MainWindow", "Choose a language"))
        self.OUTPUT_PATH_LABEL_PDF.setText(_translate("MainWindow", "Select folder path, where you want to safe a .mp3 file:"))
        self.BTN_SELECT_INPUT_PATH_PDF.setText(_translate("MainWindow", "..."))
        self.BTN_SELECT_OUTPUT_PATH_PDF.setText(_translate("MainWindow", "..."))
        self.INPUT_PATH_LABEL_PDF.setText(_translate("MainWindow", "Select pdf file path, which one you want to voice out:"))
        self.PDF_FILE_DUBBING.setText(_translate("MainWindow", "Voice out file"))
        self.PDF_BACK.setText(_translate("MainWindow", "Back"))
        self.RADIO_EN_LANG_PDF.setText(_translate("MainWindow", "Engilsh"))
        self.CHECKBOX_RU_LANG_PDF.setText(_translate("MainWindow", "Russian"))
        self.RADIO_LANG_LABEL_PDF.setText(_translate("MainWindow", "Choose a language"))
import mp3_logo_fin_pg
import mp3_logo_frst_pg


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
